# Generated by Django 4.0.4 on 2022-05-14 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_date_ordered_alter_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 14, 35, 38, 263504)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 14, 35, 38, 277016)),
        ),
    ]
